import { columns, Payment } from '@/app/(dashboard)/payments/columns';
import { DataTable } from '@/app/(dashboard)/payments/data-table';
import { PaymentsTableWrapper } from '@/app/(dashboard)/payments/PaymentsTableWrapper';

const getData = async (): Promise<Payment[]> => {
    return [
        {
            id: '728ed521',
            amount: 134,
            status: 'pending',
            fullName: 'John Doe',
            userId: '56',
            email: 'johndoe@gmail.com',
            avatarUrl: 'https://picsum.photos/id/237/200/300',
        },
        {
            id: '728ed522',
            amount: 124,
            status: 'success',
            fullName: 'Jane Doe',
            userId: '94',
            email: 'janedoe@gmail.com',
            avatarUrl: 'https://picsum.photos/id/238/200/300',
        },
        {
            id: '728ed523',
            amount: 167,
            status: 'success',
            fullName: 'Mike Galloway',
            userId: '35',
            email: 'mikegalloway@gmail.com',
            avatarUrl: 'https://picsum.photos/id/239/200/300',
        },
        {
            id: '728ed524',
            amount: 156,
            status: 'failed',
            fullName: 'Minerva Robinson',
            userId: '49',
            email: 'minerbarobinson@gmail.com',
            avatarUrl: 'https://picsum.photos/id/240/200/300',
        },
        {
            id: '728ed525',
            amount: 145,
            status: 'success',
            fullName: 'Mable Clayton',
            userId: '96',
            email: 'mableclayton@gmail.com',
            avatarUrl: 'https://picsum.photos/id/13/200/300',
        },
        {
            id: '728ed526',
            amount: 189,
            status: 'pending',
            fullName: 'Nathan McDaniel',
            userId: '19',
            email: 'nathanmcdaniel@gmail.com',
            avatarUrl: 'https://picsum.photos/id/32/200/300',
        },
        {
            id: '728ed527',
            amount: 178,
            status: 'success',
            fullName: 'Myrtie Lamb',
            userId: '52',
            email: 'myrtielamb@gmail.com',
            avatarUrl: 'https://picsum.photos/id/55/200/300',
        },
        {
            id: '728ed528',
            amount: 190,
            status: 'success',
            fullName: 'Leona Bryant',
            userId: '20',
            email: 'leonabryant@gmail.com',
            avatarUrl: 'https://picsum.photos/id/46/200/300',
        },
        {
            id: '728ed529',
            amount: 134,
            status: 'failed',
            fullName: 'Aaron Willis',
            userId: '28',
            email: 'aaronwillis@gmail.com',
            avatarUrl: 'https://picsum.photos/id/69/200/300',
        },
        {
            id: '728ed52a',
            amount: 543,
            status: 'success',
            fullName: 'Joel Keller',
            userId: '8',
            email: 'joelkeller@gmail.com',
            avatarUrl: 'https://picsum.photos/id/26/200/300',
        },
        {
            id: '728ed52b',
            amount: 234,
            status: 'pending',
            fullName: 'Daniel Ellis',
            userId: '37',
            email: 'danielellis@gmail.com',
            avatarUrl: 'https://picsum.photos/id/87/200/300',
        },
        {
            id: '728ed52c',
            amount: 345,
            status: 'success',
            fullName: 'Gordon Kennedy',
            userId: '82',
            email: 'gordonkennedy@gmail.com',
            avatarUrl: 'https://picsum.photos/id/66/200/300',
        },
        {
            id: '728ed52d',
            amount: 335,
            status: 'failed',
            fullName: 'Emily Hoffman',
            userId: '11',
            email: 'emilyhoffman@gmail.com',
            avatarUrl: 'https://picsum.photos/id/91/200/300',
        },
        {
            id: '728ed52e',
            amount: 664,
            status: 'pending',
            fullName: 'Jeffery Garrett',
            userId: '83',
            email: 'jefferygarrett@gmail.com',
            avatarUrl: 'https://picsum.photos/id/52/200/300',
        },
        {
            id: '728ed52f',
            amount: 332,
            status: 'success',
            fullName: 'Ralph Baker',
            userId: '75',
            email: 'ralphbaker@gmail.com',
            avatarUrl: 'https://picsum.photos/id/6/200/300',
        },
        {
            id: '728ed52g',
            amount: 413,
            status: 'failed',
            fullName: 'Seth Fields',
            userId: '76',
            email: 'sethfields@gmail.com',
            avatarUrl: 'https://picsum.photos/id/30/200/300',
        },
        {
            id: '728ed52h',
            amount: 345,
            status: 'pending',
            fullName: 'Julia Webb',
            userId: '18',
            email: 'juliawebb@gmail.com',
            avatarUrl: 'https://picsum.photos/id/44/200/300',
        },
        {
            id: '728ed52i',
            amount: 754,
            status: 'success',
            fullName: 'Gary Banks',
            userId: '85',
            email: 'garybanks@gmail.com',
            avatarUrl: 'https://picsum.photos/id/80/200/300',
        },
        {
            id: '728ed52j',
            amount: 643,
            status: 'failed',
            fullName: 'Flora Chambers',
            userId: '94',
            email: 'florachambers@gmail.com',
            avatarUrl: 'https://picsum.photos/id/23/200/300',
        },
        {
            id: '728ed52k',
            amount: 543,
            status: 'pending',
            fullName: 'Steve Hanson',
            userId: '45',
            email: 'stevehanson@gmail.com',
            avatarUrl: 'https://picsum.photos/id/40/200/300',
        },
        {
            id: '728ed52l',
            amount: 324,
            status: 'success',
            fullName: 'Lola Robinson',
            userId: '42',
            email: 'lolarobinson@gmail.com',
            avatarUrl: 'https://picsum.photos/id/56/200/300',
        },
        {
            id: '728ed52m',
            amount: 123,
            status: 'pending',
            fullName: 'Ethel Waters',
            userId: '64',
            email: 'ethelwaters@gmail.com',
            avatarUrl: 'https://picsum.photos/id/26/200/300',
        },
        {
            id: '728ed52n',
            amount: 422,
            status: 'failed',
            fullName: 'Grace Edwards',
            userId: '71',
            email: 'graceedwards@gmail.com',
            avatarUrl: 'https://picsum.photos/id/83/200/300',
        },
        {
            id: '728ed52o',
            amount: 712,
            status: 'success',
            fullName: 'Sallie Wong',
            userId: '11',
            email: 'salliewong@gmail.com',
            avatarUrl: 'https://picsum.photos/id/47/200/300',
        },
        {
            id: '728ed52p',
            amount: 360,
            status: 'success',
            fullName: 'Bryan Gutierrez',
            userId: '76',
            email: 'bryangutierrez@gmail.com',
            avatarUrl: 'https://picsum.photos/id/51/200/300',
        },
        {
            id: '728ed52q',
            amount: 454,
            status: 'pending',
            fullName: 'Erik Rice',
            userId: '37',
            email: 'erikrice@gmail.com',
            avatarUrl: 'https://picsum.photos/id/19/200/300',
        },
        {
            id: '728ed52r',
            amount: 382,
            status: 'success',
            fullName: 'Jordan Atkins',
            userId: '82',
            email: 'jordanatkins@gmail.com',
            avatarUrl: 'https://picsum.photos/id/2/200/300',
        },
        {
            id: '728ed52s',
            amount: 328,
            status: 'failed',
            fullName: 'Bill Brewer',
            userId: '44',
            email: 'billbrewer@gmail.com',
            avatarUrl: 'https://picsum.photos/id/60/200/300',
        },
        {
            id: '728ed52t',
            amount: 250,
            status: 'success',
            fullName: 'Edwin Morris',
            userId: '82',
            email: 'edwinmorris@gmail.com',
            avatarUrl: 'https://picsum.photos/id/36/200/300',
        },
        {
            id: '728ed52u',
            amount: 658,
            status: 'success',
            fullName: 'Harold Becker',
            userId: '66',
            email: 'haroldbecker@gmail.com',
            avatarUrl: 'https://picsum.photos/id/4/200/300',
        },
        {
            id: '728ed52v',
            amount: 691,
            status: 'success',
            fullName: 'Hannah Rodriguez',
            userId: '76',
            email: 'hannahrodriguez@gmail.com',
            avatarUrl: 'https://picsum.photos/id/58/200/300',
        },
        {
            id: '728ed52w',
            amount: 969,
            status: 'success',
            fullName: 'Zachary Beck',
            userId: '67',
            email: 'zacharybeck@gmail.com',
            avatarUrl: 'https://picsum.photos/id/89/200/300',
        },
        {
            id: '728ed52x',
            amount: 617,
            status: 'failed',
            fullName: 'Frances Potter',
            userId: '75',
            email: 'francespotter@gmail.com',
            avatarUrl: 'https://picsum.photos/id/77/200/300',
        },
        {
            id: '728ed52y',
            amount: 173,
            status: 'success',
            fullName: 'Raymond Murray',
            userId: '91',
            email: 'raymondmurray@gmail.com',
            avatarUrl: 'https://picsum.photos/id/33/200/300',
        },
        {
            id: '728ed52z',
            amount: 843,
            status: 'success',
            fullName: 'Adam Sherman',
            userId: '30',
            email: 'adamsherman@gmail.com',
            avatarUrl: 'https://picsum.photos/id/15/200/300',
        },
        {
            id: '728ed521f',
            amount: 914,
            status: 'pending',
            fullName: 'Anne Cruz',
            userId: '86',
            email: 'annecruz@gmail.com',
            avatarUrl: 'https://picsum.photos/id/71/200/300',
        },
    ];
};
const PaymentsPage = async () => {
    const data = await getData();
    return (
        <div className="">
            {/* <div className="bg-secondary mb-8 rounded-md px-4 py-2">
                <h1 className="font-semibold">All Payments</h1>
            </div> */}
            <PaymentsTableWrapper initialData={data} />
        </div>
    );
};
export default PaymentsPage;
