import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers';
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

import Navbar from '@/components/NavBar';
import Footer from '@/components/Footer';
import ChatWidget from '@/components/chat/ChatWidget';
import { ClerkProvider } from '@clerk/nextjs';
import { viVN } from '@clerk/localizations';
import BackgroundWave from '@/components/BackgroundWave';
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            localization={viVN}
            appearance={{
                layout: {
                    unsafe_disableDevelopmentModeWarnings: true,
                },
            }}
            signInUrl='/sign-in'
            signUpUrl='/sign-up'
        >
            <html lang='en'>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Navbar />
                    <div className=' '>
                        {/* Gradient */}
                        <div className='absolute inset-0 ' />

                        {/* Wave */}
                        <BackgroundWave />
                    </div>
                    <div className='mt-10'>
                        <Providers>{children}</Providers>
                    </div>
                    <Footer />
                    <div className='fixed bottom-4 right-4 z-9999'>
                        {/*
                      Lưu ý: Bạn có thể cần bọc ChatBox trong một component nhỏ hơn (ví dụ: ChatToggle)
                      để ban đầu chỉ hiển thị một biểu tượng, sau đó mở rộng ra ChatBox khi click.
                    */}
                        <ChatWidget />
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
